### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by CaptainBawa** [emmanuelsteven/Portfolio#16]
Hi @emmanuelsteven  you've done really amazing work but I think there's something you've to work on it while moving forward
![steven](https://user-images.githubusercontent.com/82339317/225837085-aa2b6be3-296a-4998-bacc-afbe9115c73b.PNG)
I can see you have an image element above your body element and I think it's not a best practice also I can see you have wrap code in the div container with a class of full-wrap and I think its not a best practice

**Comment by MesakDuduCoder** [comment]
Your code is looking good Steven it was clean and you just need to add alt text for images.

**Comment by emmanuelsteven** [comment]
thanks you guys for your kind review i would make these corrections
